name: tf-sur
channels:
    - apple
    - conda-forge
dependencies:
    - python<3.10
    - pip>=19.0
    - jupyter
    - tensorflow-deps
    - tensorflow-datasets
    - scikit-learn
    - scipy
    - pandas
    - pandas-datareader
    - matplotlib
    - pillow
    - tqdm
    - requests
    - h5py
    - pyyaml
    - pip:
        - tensorflow-macos
        - tensorflow-metal
        - wandb
        - fastcore
